# Site settings
title: Statorial
description: Tutorials on implementing statistical methods
google_analytics: UA-135308301-1

plugins:
  # search engine optimization
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: /:title

# http://jekyllrb.com/docs/collections/
collections:
  varinf:
    output: true
    permalink: /varinf/:title/

defaults:
  -
    scope:
      path: ""
    values:
      comments: on
