# Site settings
title: Statorial
description: Tutorials on implementing statistical methods
google_analytics: G-RJBL4JRZQ8

plugins:
  # search engine optimization
  - jekyll-seo-tag
  # create sitemap
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: /:title

# http://jekyllrb.com/docs/collections/
collections:
  varinf:
    output: true
    permalink: /varinf/:title/

defaults:
  -
    scope:
      path: ""
    values:
      comments: on
