# Site settings
title: Statorial
description: Tutorials on implementing statistical methods

# Build settings
markdown: kramdown
permalink: /:title

# http://jekyllrb.com/docs/collections/
collections:
  varinf:
    output: true
    permalink: /varinf/:title/

defaults:
  -
    scope:
      path: ""
    values:
      comments: on
