# theme: jekyll-theme-slate
theme: jekyll-theme-cayman
permalink: /:title #pretty

# http://jekyllrb.com/docs/collections/
collections:
  varinf:
    output: true
    permalink: /varinf/:title/

defaults:
  -
    scope:
      path: ""
    values:
      comments: on
